In [1]:
for x in range (2000,3200):
    if(x%7==0) and (x%5==0):
        print(x, end=';')

2030;2065;2100;2135;2170;2205;2240;2275;2310;2345;2380;2415;2450;2485;2520;2555;2590;2625;2660;2695;2730;2765;2800;2835;2870;2905;2940;2975;3010;3045;3080;3115;3150;3185;

In [2]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=int(input("Enter number: "))
print(factorial(n))

Enter number: 8
40320


In [3]:
n=int(input("Enter number: "))
d={i:i*i for i in range(1,n+1)}
print(d)

Enter number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [16]:
def remove_char(str, n):
    f= str[:n]
    b= str[n+1:]
    return f + b
print(remove_char('kitten', 0))

itten


In [27]:
import numpy as np 
x=np.array([[0,1],[2,3],[4,5]])
print("Original array elements:")
print(a)
print("Array to list:")
print(a.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [29]:
import numpy as np
a = np.array([0,1,2])
b = np.array([2,1,0])
print("\nOriginal array1:")
print(a)
print("\nOriginal array1:")
print(b)
print("\nCovariance matrix of the said arrays:\n",np.cov(a, b))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [ ]:
import math 
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))
    
print(','.join(value))